run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
